<?php
include_once("inc/auth.inc.php");
include_once("inc/header.inc.php");
/******************************验证********************************************/
//验证函数
function check_type($fieldType, $fieldData){
   switch($fieldType){
		case "N":
			$fieldData = "'" . $fieldData;
			break;
		case "S":
			$fieldData = $fieldData == '0'?_("否"):_("是");
		case "NN":
			$fieldData = number_format($fieldData, 2, ".", ",");
			break;
		case "D":
			if($fieldData == "0000-00-00"){
				$fieldData = "";
			}
			break;
		case "NA":					//资产性质
			if($fieldData == "01"){
				$fieldData = _("资产");
			}else{
				$fieldData = _("费用");
			}
			break;
                case "RU":
                        $query_name = "SELECT USER_NAME from USER where USER_ID = '$fieldData'";
                        $cursor_name= exequery(TD::conn(),$query_name);
                        if($ROW_NAME=mysql_fetch_array($cursor_name)){
                           $fieldData = $ROW_NAME["USER_NAME"] != ""?$ROW_NAME["USER_NAME"]:$fieldData;
                        }
                        break;
		default:
			$fieldData = "" . $fieldData;
	}
	return $fieldData;
}



/*******************************生成Excel*************************************/
function createPHPExcelObj(){	//创建Excel对象
	$objExcel = new PHPExcel();
	
	return $objExcel;
}


function setProperties($objExcel, $Creator, $subject){//设置文档属性
	//设置文档基本属性
	$objProps = $objExcel->getProperties();
	$objProps->setCreator(change_encode($Creator));
	$objProps->setLastModifiedBy(change_encode($Creator));
	$objProps->setTitle("Office XLS Report Document");
	$objProps->setSubject(change_encode($subject));
	$objProps->setDescription("Report document, generated by PHPExcel.");
	$objProps->setKeywords("office excel PHPExcel");
	$objProps->setCategory("Report");

	$objActSheet = $objExcel->getActiveSheet();    
	   
	//设置当前活动sheet的名称
	$name = iconv(MYOA_DB_CHARSET,"UTF-8",$subject);
	$objActSheet->setTitle($name);

	return $objActSheet;
}

function setTitle($objActSheet, $thArr, $colWidth){//设置内容
	$colCount = count($thArr);
	//开始列
	$startCol	= "A";
	//结束列
	$endCol		= chr(65 + ($colCount -1));
	
	/**********************排版样式*************************/
	//表头样式
	//设置标题
	//$objActSheet->mergeCells("B1:" . $endCol . "1"); //合并标题单元格
	
	$styleTable = $objActSheet->getStyle("A:$endCol");
	$fontTable = $styleTable->getFont();
	$fontTable->setName(change_encode(_("微软雅黑")));

	//标题样式
	$styleA1 = $objActSheet->getStyle('A1'); 
	$fontA1 = $styleA1->getFont(); 
	$fontA1->setName(change_encode(_("微软雅黑")));
	$fontA1->setSize('11');
	$objAlignA1 = $styleA1->getAlignment();  
	$objAlignA1->setHorizontal(PHPExcel_Style_Alignment::VERTICAL_CENTER);  
	$objAlignA1->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

	//标题
	//$objActSheet->setCellValue('B1', $objActSheet->getTitle());

	//循环输出th
	for($i = 0; $i < $colCount; $i ++){
		$col = chr(65 + $i);
		$objActSheet->getColumnDimension("$col")->setWidth($colWidth[$i]);				//设置宽度
		$objActSheet->setCellValue($col . "1", change_encode($thArr[$i]));
	}
	
	return $objActSheet;
}

function setContents($fieldArr, $cursor, $objActSheet, $type){
		$count = 2;
	while($ROW=mysql_fetch_array($cursor)){
		$colName = 65;
	
		for($i = 0; $i <count($fieldArr); $i++ ){
			$objActSheet->setCellValue(chr($colName) . $count, change_encode(check_type($type[$i], $ROW[($fieldArr[$i])])));
			$colName ++;
		}
		$count ++;
	}
	
	return $objActSheet;
}

/*********************************表格样式**************************************/
function tabStyle($objActSheet, $cols, $rows){
	$colName = 65;

	for($i = 1; $i <= ($rows+1); $i++){
		for($k = 0; $k < $cols; $k++){
			$objActSheet->getStyle(chr($colName + $k) . $i)->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
			$objActSheet->getStyle(chr($colName + $k) . $i)->getBorders()->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
		}
	}
	/******************************外边框****************************/
	//上
	$objActSheet->getStyle("A1:" . chr($colName + $cols - 1) . ($rows + 1))->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//右
	$objActSheet->getStyle("A1:" . chr($colName + $cols - 1) . ($rows + 1))->getBorders()->getRight()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//下
	$objActSheet->getStyle("A1:" . chr($colName + $cols - 1) . ($rows + 1))->getBorders()->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//左
	$objActSheet->getStyle("A1:" . chr($colName + $cols - 1) . ($rows + 1))->getBorders()->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);


}
?>