<?
include_once("inc/auth.inc.php");

/******************************验证********************************************/
//验证函数
function check_type($fieldType, $fieldData){
   switch($fieldType){
		case "N":
			//$fieldData = "'" . $fieldData;
			$fieldData = "". $fieldData;
			break;
		case "S":
			$fieldData = $fieldData == '0'?_("否"):_("是");
		case "NN":
			$fieldData = number_format($fieldData, 2, ".", ",");
			break;
		case "D":
			if($fieldData == "0000-00-00"){
				$fieldData = "";
			}
			break;
		case "NA":					//资产性质
			if($fieldData == "01"){
				$fieldData = _("资产");
			}else{
				$fieldData = _("费用");
			}
			break;
                case "RU":
                        $query_name = "SELECT USER_NAME from USER where USER_ID = '$fieldData'";
                        $cursor_name= exequery(TD::conn(),$query_name);
                        if($ROW_NAME=mysql_fetch_array($cursor_name)){
                           $fieldData = $ROW_NAME["USER_NAME"] != ""?$ROW_NAME["USER_NAME"]:$fieldData;
                        }
                        break;
		default:
			$fieldData = "" . $fieldData;
	}
	return $fieldData;
}



/*******************************生成Excel*************************************/
function createPHPExcelObj(){	//创建Excel对象
	$objExcel = new PHPExcel();
	
	return $objExcel;
}


function setProperties($objExcel, $Creator, $subject){//设置文档属性

	//设置文档基本属性
	$objProps = $objExcel->getProperties();
	$objProps->setCreator(change_encode($Creator));
	$objProps->setLastModifiedBy(change_encode($Creator));
	$objProps->setTitle("Office XLS Report Document");
	$objProps->setSubject(change_encode($subject));
	$objProps->setDescription("Report document, generated by PHPExcel.");
	$objProps->setKeywords("office excel PHPExcel");
	$objProps->setCategory("Report");

	$objActSheet = $objExcel->getActiveSheet();    
	   
	//设置当前活动sheet的名称
	$name = iconv(MYOA_CHARSET,"UTF-8",$subject);
	$objActSheet->setTitle($name);

	return $objActSheet;
}

function setTitle($objActSheet, $thArr, $colWidth){//设置内容
	$colCount = count($thArr);
	//开始列
	$startCol	= "A";
	//结束列
	$endCol = getExcelValue($colCount);

	/**********************排版样式*************************/
	//表头样式
	//设置标题
	//$objActSheet->mergeCells("B1:" . $endCol . "1"); //合并标题单元格
	
	$styleTable = $objActSheet->getStyle("A:$endCol");
	
	$fontTable = $styleTable->getFont();
	$fontTable->setName(change_encode(_("微软雅黑")));

	//标题样式
	$styleA1 = $objActSheet->getStyle('A1'); 
	$fontA1 = $styleA1->getFont(); 
	$fontA1->setName(change_encode(_("微软雅黑")));
	$fontA1->setSize('11');
	$objAlignA1 = $styleA1->getAlignment();  
	$objAlignA1->setHorizontal(PHPExcel_Style_Alignment::VERTICAL_CENTER);  
	$objAlignA1->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

	//标题
	//$objActSheet->setCellValue('B1', $objActSheet->getTitle());

	//循环输出th
	for($i = 0; $i < $colCount; $i ++)
	{
		if($i>0)
		{
			$col = getExcelValue($i+1);
		}
		else
		{
			$col = chr(65 + $i);
		}
		$objActSheet->getColumnDimension("$col")->setWidth($colWidth[$i]);				//设置宽度
		$objActSheet->setCellValue($col . "1", change_encode($thArr[$i]));
	}
	return $objActSheet;
}

function setContents($fieldArr, $cursor, $objActSheet, $type)
{
	$count = 2;
	while($ROW3=mysql_fetch_array($cursor))
	{
		$CPTL_ID=$ROW3["CPTL_ID"];
		
		//获取自定义字段数据
		$USER_DEF_ARRAY=array();
		$query5="select * from FIELDSETTING where TABLENAME='CP_CPTL_INFO'";
		$cursor5=exequery(TD::conn(),$query5);
		while($ROW5=mysql_fetch_array($cursor5))
		{
			$FIELDNO    = $ROW5["FIELDNO"];
			$STYPE      = $ROW5["STYPE"];
			$TYPENAME   = $ROW5["TYPENAME"];
			$TYPEVALUE  = $ROW5["TYPEVALUE"];
			$TYPECODE   = $ROW5["TYPECODE"];
			if(!in_array($FIELDNO, $fieldArr))
				continue;
			$query1 = "select ITEM_DATE from FIELD_DATE where TABLENAME='CP_CPTL_INFO' and FIELDNO='$FIELDNO' and IDENTY_ID='$CPTL_ID' ";
			$cursor1=exequery(TD::conn(),$query1);
			if($ROW1=mysql_fetch_array($cursor1)){
				$ITEM_DATE = $ROW1["ITEM_DATE"];
				if(in_array($STYPE, array('D', 'R', 'C')))
				{
					if($TYPENAME && $TYPEVALUE)
					{
						$tmp_name_arr = explode(',', $TYPENAME);
						$tmp_val_arr = explode(',', $TYPEVALUE);
						if(in_array($ITEM_DATE, $tmp_val_arr))
						{
							$USER_DEF_ARRAY[$FIELDNO] = $tmp_name_arr[array_search($ITEM_DATE, $tmp_val_arr)];
						}
					}
					elseif($TYPECODE)
					{
						$query_code = "SELECT CODE_NAME FROM SYS_CODE WHERE PARENT_NO = '$TYPECODE' AND CODE_NO = '$ITEM_DATE'";
						$cursor_code = exequery(TD::conn(), $query_code);
						if($row_code = mysql_fetch_array($cursor_code))
						{
							$USER_DEF_ARRAY[$FIELDNO] = $row_code['CODE_NAME'];
						}
					}
					else
					{
						$USER_DEF_ARRAY[$FIELDNO]=$ITEM_DATE;
					}
				}
				else
				{
					$USER_DEF_ARRAY[$FIELDNO]=$ITEM_DATE;
				}
			}
		}
		$result_arr=array_merge($ROW3,$USER_DEF_ARRAY);
				$colName = 65;
	
		for($i = 0; $i <count($fieldArr); $i++ )
		{
			if($i>0)
			{
				$col = getExcelValue($i+1);
			}
			else
			{
				$col = chr(65 + $i);
			}
			
			$objActSheet->setCellValue($col . $count, change_encode(check_type($type[$i], $result_arr[($fieldArr[$i])])));
			$colName ++;
		}
		$count ++;
	}
	return $objActSheet;
}
//生成excel列 *当数列超过Z时必用*
function getExcelValue($index)
{
    $index = (int)$index;
	if($index <= 0)
	{
		return;
	}
    $dimension = ceil(log(25 * $index + 26, 26)) - 1;  //算结果一共有几位，实际算的是位数减1，记住是26进制的位数
    $n = $index - 26 * (pow(26, $dimension- 1) - 1) / 25; //算结果在所在位数总数中排第几个
    $n--; //转化为索引
 
    return str_pad(
        str_replace(
            array_merge(range(0, 9), range('a', 'p')), 
            range('A', 'Z'), base_convert($n, 10, 26)
        ), $dimension, 'A', STR_PAD_LEFT
    );
}

/*********************************表格样式**************************************/
function tabStyle($objActSheet, $cols, $rows)
{	
	$colName = 65;
	for($i = 1; $i <= ($rows+1); $i++)
	{
		for($k = 0; $k < $cols; $k++)
		{
			if($k>0)
			{
				$col = getExcelValue($k+1);
			}
			else
			{
				$col = chr(65);
			}
			$objActSheet->getStyle($col . $i)->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
			$objActSheet->getStyle($col . $i)->getBorders()->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
		}
	}
	/******************************外边框****************************/
	//上	
	$objActSheet->getStyle("A1:" . getExcelValue($cols) . ($rows + 1))->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//右
	$objActSheet->getStyle("A1:" . getExcelValue($cols) . ($rows + 1))->getBorders()->getRight()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//下
	$objActSheet->getStyle("A1:" . getExcelValue($cols) . ($rows + 1))->getBorders()->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);
	//左
	$objActSheet->getStyle("A1:" . getExcelValue($cols) . ($rows + 1))->getBorders()->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THICK);


}
?>